minijava  : AsmRefiner.cpp MiniJava.cpp MiniJava2Decaf.cpp

	/usr/local/gcc-4.1.2/bin/g++ -I /afs/cs.pitt.edu/usr0/yongli/boost_1_42_0 -Wl,-rpath=/usr/local/gcc-4.1.2/lib64/ AsmRefiner.cpp MiniJava.cpp MiniJava2Decaf.cpp -o minijava