#!/bin/sh -f
#
# run
# Usage:  run minijava-file
# ./dcc <out.minijava> tmp.asm
# Compiles minijava-file.
#

COMPILER=dcc

if [ $# -lt 1 ]; then
  echo "Run script error: The run script takes one argument, the path to a minijava file."
  exit 1;
fi
if [ ! -x $COMPILER ]; then
  echo "Run script error: Cannot find $COMPILER executable!"
  echo "(You must run this script from the directory containing your $COMPILER executable.)"
  exit 1;
fi
if [ ! -r $1 ]; then
  echo "Run script error: Cannot find minijava input file named '$1'."
  exit 1;
fi

echo "-- $COMPILER <$1 >tmp.asm"
./$COMPILER < $1 > tmp.asm 2>tmp.errors
if [ $? -ne 0 -o -s tmp.errors ]; then
  echo "Run script error: errors reported from $COMPILER compiling '$1'."
  echo " "
  cat tmp.errors
  exit 1;
fi

echo " "
echo " "
exit 0;
